---
title: "Panoramas da Biodiversidade Brasileira"
subtitle: "Projeto piloto: Anfíbios"
author : "Ricardo Rodrigues da Silveira Filho | Adrian Antonio Garda"
output: 
    ioslides_presentation:
        widescreen: true
        smaller: true
        css: ../source/css/caatinga-slides_css.css
        highlight: monochrome
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}

# setup for all chunks
knitr::opts_chunk$set(echo = FALSE)

```


```{css}

.gdbar img {
  width: 253px !important;
  height: 79px !important;
  margin: 8px 8px;
}

.gdbar {
  width: 400px !important;
  height: 95px !important;
}

.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    margin: 5px;
   
    text-align: right;
}

slides > slide:not(.nobackground):before {
  width: 75px;
  height: 25px;
  background-size: 75px 25px;
}

```


# Atualizações...

## Atualizações | Laboratório {.flexbox .vcenter}

<h3>Volta ao trabalho presencial!</h3>

</br> </br>

- Organização pós pandemia

- Instalação de experimento a longo prazo ([8 dias/mês]{.underline})

- Treinamento de pessoal (graduação, pós)

- *Já ouviu a palavra do Hadley hoje?*

- Interação


## Atualizações | Pesquisa {.flexbox .vcenter}

- Dados de anfíbios e répteis **coletados**

- Início do desenvolvimento:

	- Pacote **panppbio** para o *R*

	- Função para coleta de dados no *BOLD Systems*

	- *Dashboard* em construção


# Produtos esperados

## Pacote **panppbio** | Auxiliando outros grupos de pesquisa

- Porquê?

- <https://github.com/rsilveirafh/panppbio>

- Lista de espécies
	- Anfíbios (**ok**)
	- Aves (**--**)
	- Mamíferos (**ok -- Hernani**)
	- Peixes (**?**)
	- Répteis (**ok**)

## Pacote **panppbio** | Continuação

- BOLD Systems (**OK**)
	- Coletar dados baseado em duas pesquisas:
		- Classe + País
		- Nomes das espécies
- NCBI (**0%**)
	- Idem acima
- IUCN (**0% -- Sem Token para API**)
	- Status, espacial e *trait*
- GBIF (**0%**)
	- *Trait* e espacial
- Correção de nomes e atualizações

</br> </br>
>> **Entrega prevista: ~ agosto 2023**


## Dashboard? | Melhorando a forma de comunicação

<h5>1\. Dados gerais</h5>
<h5>2\. Gráficos</h5>
<h5>3\. Mapas</h5>
<h5>4\. Tabelas</h5>
<h5>5\. Exportando</h5>

</br> </br> </br> </br> </br> </br> </br> </br> </br> </br>
>> **Entrega prevista: ~ maio 2023**


## Onde me encontrar? | github.com/rsilveirafh

<small>

<div class="columns-1">

- Blog:
    - <a href="https://rsilveirafh.netlify.app/about.html">https://rsilveirafh.netlify.app/</a>

- CV:
    - <a href="https://github.com/rsilveirafh/blogR/blob/6013efef2292427bfbead7f12d6dcff443c1be08/Curriculum-Vitae-RRdSF.pdf">currículo</a>

- LinkedIn:
    - <a href="https://www.linkedin.com/in/rsilveirafh/">https://www.linkedin.com/in/rsilveirafh/</a>
    
- E-mail
    - <a href="mailto:ricardodasilveira@gmail.com">ricardodasilveira\@gmail.com</a>

</br> </br> </br> </br> </br>

**Obrigado!**

</small>
