---
title: "Gráficos"
output: 
    html_document:
    logo: ../source/logos/ppbio.png
    vertical_layout: scroll
    css: css/basic_css.css
    theme: bootstrap
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(highcharter)
library(plotly)
library(tidyverse)
source("../source/R/utils.R")

```


## I. Número de ocorrências de dados genéticos


### Por Espécie (`highcharter`)
```{r}

search_amp_spp |>  
	count(species_name) |> 
	arrange(n) |> 
	hchart("bar", 
		   hcaes(x = species_name, 
		   	  y = n),
		   name = "Quantidade") |> 
	hc_yAxis(hc = _, 
			 title = list(text = "Número de ocorrências")) |> 
	hc_xAxis(hc = _, 
			 title = list(text = "Espécies"))
	
```


### Por Família (`highcharter`)
```{r}

search_amp_spp |>  
	count(family_name) |> 
	arrange(n) |> 
	hchart("bar", 
		   hcaes(x = family_name, 
		   	  y = n),
		   name = "Quantidade") |> 
	hc_yAxis(hc = _, 
			 title = list(text = "Número de ocorrências")) |> 
	hc_xAxis(hc = _, 
			 title = list(text = "Famílias"))
	

```


## II. Algumas mudanças (`ggplot2` + `plotly`)
```{r}
a <- ggplot(count(search_amp_spp, family_name), aes(x = reorder(family_name, n), y = n)) +
	geom_bar(stat = "identity", width = .7,
			 position = "dodge", fill = "#FF5C00") +
	geom_text(aes(label = n), size = 3,
			  position = position_dodge2(width = .9),
			  hjust = -0.15, vjust = .5) +
	scale_x_discrete(limits = rev) +
	coord_flip() +
	xlab("Amphibian Families") +
	ylab("Total of occurrences") +
	ylim(0, 1560) +
	theme_bw() +
	theme(axis.title = element_text(size = 12, face = "bold"),
		  axis.text.x = element_text(size = 12),
		  axis.text.y = element_text(size = 12)) 

ggplotly(a)
```


