---
title: "Datasets"
output: 
  html_document:
    logo: ../source/logos/ppbio.png
    vertical_layout: scroll
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(broom) # tidy() function
library(here) # fix working directory issues
library(maptools) # required for "broom"
library(patchwork) # gather the plots
library(rgdal) # readOGR() function
library(rgeos) # required for "broom"

```

## Distribuição dos dados genéticos


```{r}

brazil <- readOGR(dsn = here::here("/media/ricardo/backup/Mapas/Shapes/Biomas"),
				  layer = "bioma")

brazil@proj4string <- CRS("+proj=longlat +datum=WGS84")

brazil_tidy <- tidy(brazil)

brazil_cor <- brazil_tidy %>%
	mutate(id = case_when(
		id == "0" ~ "Amazônia",
		id == "1" ~ "Caatinga",
		id == "2" ~ "Cerrado",
		id == "3" ~ "Pampa",
		id == "4" ~ "Pantanal",
		id == "5" ~ "Mata Atlântica"
	),
	colors = case_when(
		id == "Amazônia" ~ "#429238",
		id == "Caatinga" ~ "#A05C47",
		id == "Cerrado" ~ "#D7CD7A",
		id == "Pampa" ~ "#9EAFB7",
		id == "Pantanal" ~ "#C678B8",
		id == "Mata Atlântica" ~ "#9FD5C6"
	))


sa <- readOGR(dsn = here::here("/media/ricardo/backup/Mapas/Shapes/samerica"),
			  layer = "samer")

sa@proj4string <- brazil@proj4string

sa_tidy <- tidy(sa)




B <- ggplot() +
	geom_polygon(data = sa_tidy, aes(long, lat, group = group),
				 fill = "gray", color = "black", alpha = .6, size = .1) +
	geom_polygon(data = brazil_cor, aes(x = long, y = lat, group = group),
				 fill = brazil_cor$colors, color = "black", size = .2, alpha = .7) +
	geom_point(data = br_dataAmp, aes(x = lon, y = lat),
			   size = .7, colour = "#FF5C00") +
	labs(x = "Longitude", y = "Latitude") +

	theme_bw() +
	theme(panel.border = element_rect(color = "black", fill = NA),
		  panel.background = element_rect(fill = "aliceblue"),
		  axis.title = element_text(size = 13, face = "bold"),
		  axis.text.x = element_text(size = 13),
		  axis.text.y = element_text(size = 13)) +
	coord_fixed(xlim = c(-73.5, -33),
				ylim = c(-33, 5))


A + B
```


